# Generated by Django 2.1.1 on 2018-09-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=666)),
                ('geoX', models.FloatField(verbose_name='Geocode Latitude')),
                ('geoY', models.FloatField(verbose_name='Geocode Longitude')),
                ('action', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
            ],
        ),
    ]
