# Generated by Django 2.1.1 on 2018-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180915_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.SlugField(max_length=200),
        ),
    ]
